version: "3.8"

services:
  backend_database:
    container_name: "mysql"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "mision31"
      MYSQL_DATABASE: "PVelazquezDB"
      MYSQL_USER: "pvelazquez$%#543"
      MYSQL_PASSWORD: "EstaEsLaContraseniaNumero1234ParaDB"
    volumes:
      - default-volume-mysql:/var/lib/mysql:rw

  backend_azurite:
    container_name: "azurite"
    image: mcr.microsoft.com/azure-storage/azurite:3.27.0
    volumes:
      - default-volume-azurite:/data mcr.microsoft.com/azure-storage/azurite


  backend_mailhog:
    container_name: "mailhog"
    image: mailhog/mailhog
    expose:
      - 8025
    ports:
      - "8025:8025"


  backend:
    build:
      dockerfile: backend.Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      backend_database:
        condition: service_started
      backend_azurite:
        condition: service_started
      backend_mailhog:
        condition: service_started



volumes:
  default-volume-azurite:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./project-data/azurite
  default-volume-mysql:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./project-data/mysql