spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://backend_database:5432/backend_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
